# port of HTTP
port: 7890

# port of SOCKS5
socks-port: 1080

# (HTTP and SOCKS5 in one port)
# mixed-port: 7890

# redir port for Linux and macOS
# redir-port: 7892

allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:

rules:
  - DOMAIN-SUFFIX,smtp,DIRECT
  - MATCH,cn
