# port of HTTP
port: 7890

# port of SOCKS5
socks-port: 7891

# (HTTP and SOCKS5 in one port)
# mixed-port: 7890

# redir port for Linux and macOS
# redir-port: 7892

allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 国家选择
      - 负载均衡
      - 失败切换
      - DIRECT
  - name: 自动选择
    type: url-test
    use:
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 手动选择
    type: select
    use:
      - all
  - name: 国家选择
    type: select
    proxies:
      - 美国节点
      - 狮城节点
      - 香港节点
      - 其他国家
  - name: 负载均衡
    type: load-balance
    use:
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 失败切换
    type: fallback
    use:
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 苹果服务
    type: select
    proxies:
      - 节点选择
      - 选择国家
      - DIRECT
  - name: 谷歌服务
    type: select
    proxies:
      - 节点选择
      - 选择国家
      - DIRECT
  - name: Emby视频
    type: select
    proxies:
      - 节点选择
      - 选择国家
      - DIRECT
  - name: 美国节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - us
  - name: 香港节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - hk
  - name: 狮城节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - sg
  - name: 其他国家
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - others

proxy-providers:
  us:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-us.yml"
    path: TopFreeProxies/provider-us.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  hk:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-hk.yml"
    path: TopFreeProxies/provider-jp.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  sg:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-sg.yml"
    path: TopFreeProxies/provider-sg.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  others:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-others.yml"
    path: TopFreeProxies/provider-others.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  all:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-all.yml"
    path: TopFreeProxies/provider.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

rule-providers: # rule-providers frome Logyalsoldier/clash-rules
  Reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./TopFreeProxies/ruleset/reject.yaml
    interval: 86400

  iCloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./TopFreeProxies/ruleset/icloud.yaml
    interval: 86400

  Apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./TopFreeProxies/ruleset/apple.yaml
    interval: 86400

  Google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./TopFreeProxies/ruleset/google.yaml
    interval: 86400

  Proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./TopFreeProxies/ruleset/proxy.yaml
    interval: 86400

  Direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./TopFreeProxies/ruleset/direct.yaml
    interval: 86400

  Private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./TopFreeProxies/ruleset/private.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./TopFreeProxies/ruleset/telegramcidr.yaml
    interval: 86400

rules:
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,xray,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,leaf,DIRECT
  - PROCESS-NAME,v2ray.exe,DIRECT
  - PROCESS-NAME,xray.exe,DIRECT
  - PROCESS-NAME,naive.exe,DIRECT
  - PROCESS-NAME,trojan.exe,DIRECT
  - PROCESS-NAME,trojan-go.exe,DIRECT
  - PROCESS-NAME,ss-local.exe,DIRECT
  - PROCESS-NAME,privoxy.exe,DIRECT
  - PROCESS-NAME,leaf.exe,DIRECT
  - PROCESS-NAME,Surge,DIRECT
  - PROCESS-NAME,Surge 2,DIRECT
  - PROCESS-NAME,Surge 3,DIRECT
  - PROCESS-NAME,Surge 4,DIRECT
  - PROCESS-NAME,Surge%202,DIRECT
  - PROCESS-NAME,Surge%203,DIRECT
  - PROCESS-NAME,Surge%204,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - PROCESS-NAME,aria2c.exe,DIRECT
  - PROCESS-NAME,BitComet.exe,DIRECT
  - PROCESS-NAME,fdm.exe,DIRECT
  - PROCESS-NAME,NetTransport.exe,DIRECT
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - PROCESS-NAME,Thunder.exe,DIRECT
  - PROCESS-NAME,ThunderVIP.exe,DIRECT
  - PROCESS-NAME,transmission-daemon.exe,DIRECT
  - PROCESS-NAME,transmission-qt.exe,DIRECT
  - PROCESS-NAME,uTorrent.exe,DIRECT
  - PROCESS-NAME,WebTorrent.exe,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT

#  - RULE-SET,Direct,DIRECT
  - RULE-SET,Proxy,节点选择
  - RULE-SET,Reject,REJECT
  - RULE-SET,Private,REJECT
  - RULE-SET,iCloud,苹果服务,no-resolve
  - RULE-SET,Apple,苹果服务,no-resolve
  - RULE-SET,Google,谷歌服务
  - RULE-SET,Telegram,节点选择

  - DOMAIN-SUFFIX,emby.wtf,Emby视频,no-resolve
  - DOMAIN-SUFFIX,bitwarden.net,DIRECT,no-resolve
  - DOMAIN-SUFFIX,bitwarden.com,DIRECT,no-resolve

  - GEOIP,CN,DIRECT
  - MATCH,节点选择