# port of HTTP
port: 7890

# port of SOCKS5
socks-port: 7891

# (HTTP and SOCKS5 in one port)
# mixed-port: 7890

# redir port for Linux and macOS
# redir-port: 7892

allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:

proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 国家选择
      - 负载均衡
      - 失败切换
      - DIRECT
  - name: 自动选择
    type: url-test
    use:
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 手动选择
    type: select
    use:
      - all
  - name: 国家选择
    type: select
    proxies:
      - 美国节点
      - 狮城节点
      - 香港节点
      - 其他国家
  - name: 社交服务
    type: select
    proxies:
      - 节点选择
      - 国家选择
      - DIRECT
  - name: 苹果服务
    type: select
    proxies:
      - 节点选择
      - 国家选择
      - DIRECT
  - name: 微软服务
    type: select
    proxies:
      - 节点选择
      - 国家选择
      - DIRECT
  - name: 谷歌服务
    type: select
    proxies:
      - 节点选择
      - 国家选择
      - DIRECT
  - name: Emby视频
    type: select
    proxies:
      - 节点选择
      - 国家选择
      - DIRECT
  - name: 负载均衡
    type: load-balance
    use:
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 失败切换
    type: fallback
    use:
      - all
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 美国节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - us
  - name: 香港节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - hk
  - name: 狮城节点
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - sg
  - name: 其他国家
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - others

proxy-providers:
  us:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-us.yml"
    path: TopFreeProxies/provider-us.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  hk:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-hk.yml"
    path: TopFreeProxies/provider-jp.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  sg:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-sg.yml"
    path: TopFreeProxies/provider-sg.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  others:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-others.yml"
    path: TopFreeProxies/provider-others.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  all:
    type: http
    url: "https://raw.fastgit.org/alanbobs999/TopFreeProxies/master/update/provider/eternity-all.yml"
    path: TopFreeProxies/provider.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

rule-providers: # rule-providers frome Logyalsoldier/clash-rules
  Reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./TopFreeProxies/ruleset/reject.yaml
    interval: 86400
  iCloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./TopFreeProxies/ruleset/icloud.yaml
    interval: 86400
  Apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./TopFreeProxies/ruleset/apple.yaml
    interval: 86400
  Google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./TopFreeProxies/ruleset/google.yaml
    interval: 86400
  Proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./TopFreeProxies/ruleset/proxy.yaml
    interval: 86400
  Direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./TopFreeProxies/ruleset/direct.yaml
    interval: 86400
  Private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./TopFreeProxies/ruleset/private.yaml
    interval: 86400
  Telegram:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./TopFreeProxies/ruleset/telegramcidr.yaml
    interval: 86400

rules:
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,xray,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,leaf,DIRECT
  - PROCESS-NAME,v2ray.exe,DIRECT
  - PROCESS-NAME,xray.exe,DIRECT
  - PROCESS-NAME,naive.exe,DIRECT
  - PROCESS-NAME,trojan.exe,DIRECT
  - PROCESS-NAME,trojan-go.exe,DIRECT
  - PROCESS-NAME,ss-local.exe,DIRECT
  - PROCESS-NAME,privoxy.exe,DIRECT
  - PROCESS-NAME,leaf.exe,DIRECT
  - PROCESS-NAME,Surge,DIRECT
  - PROCESS-NAME,Surge 2,DIRECT
  - PROCESS-NAME,Surge 3,DIRECT
  - PROCESS-NAME,Surge 4,DIRECT
  - PROCESS-NAME,Surge%202,DIRECT
  - PROCESS-NAME,Surge%203,DIRECT
  - PROCESS-NAME,Surge%204,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - PROCESS-NAME,aria2c.exe,DIRECT
  - PROCESS-NAME,BitComet.exe,DIRECT
  - PROCESS-NAME,fdm.exe,DIRECT
  - PROCESS-NAME,NetTransport.exe,DIRECT
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - PROCESS-NAME,Thunder.exe,DIRECT
  - PROCESS-NAME,ThunderVIP.exe,DIRECT
  - PROCESS-NAME,transmission-daemon.exe,DIRECT
  - PROCESS-NAME,transmission-qt.exe,DIRECT
  - PROCESS-NAME,uTorrent.exe,DIRECT
  - PROCESS-NAME,WebTorrent.exe,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT

  - DOMAIN-SUFFIX,www.gstatic.com,节点选择
  - DOMAIN-SUFFIX,emby.wtf,Emby视频,no-resolve
  - DOMAIN-SUFFIX,bitwarden.net,DIRECT,no-resolve
  - DOMAIN-SUFFIX,bitwarden.com,DIRECT,no-resolve

  - PROCESS-NAME,OneDrive,微软服务
  - PROCESS-NAME,OneDriveUpdater,微软服务
  - DOMAIN-KEYWORD,1drv,微软服务
  - DOMAIN-KEYWORD,onedrive,微软服务
  - DOMAIN-KEYWORD,skydrive,微软服务
  - DOMAIN-SUFFIX,livefilestore.com,微软服务
  - DOMAIN-SUFFIX,oneclient.sfx.ms,微软服务
  - DOMAIN-SUFFIX,onedrive.com,微软服务
  - DOMAIN-SUFFIX,onedrive.live.com,微软服务
  - DOMAIN-SUFFIX,photos.live.com,微软服务
  - DOMAIN-SUFFIX,sharepoint.com,微软服务
  - DOMAIN-SUFFIX,sharepointonline.com,微软服务
  - DOMAIN-SUFFIX,skydrive.wns.windows.com,微软服务
  - DOMAIN-SUFFIX,spoprod-a.akamaihd.net,微软服务
  - DOMAIN-SUFFIX,storage.live.com,微软服务
  - DOMAIN-SUFFIX,storage.msn.com,微软服务
  - DOMAIN-KEYWORD,1drv,微软服务
  - DOMAIN-KEYWORD,microsoft,微软服务
  - DOMAIN-SUFFIX,aadrm.com,微软服务
  - DOMAIN-SUFFIX,acompli.com,微软服务
  - DOMAIN-SUFFIX,acompli.net,微软服务
  - DOMAIN-SUFFIX,aka.ms,微软服务
  - DOMAIN-SUFFIX,akadns.net,微软服务
  - DOMAIN-SUFFIX,aspnetcdn.com,微软服务
  - DOMAIN-SUFFIX,assets-yammer.com,微软服务
  - DOMAIN-SUFFIX,azure.com,微软服务
  - DOMAIN-SUFFIX,azure.net,微软服务
  - DOMAIN-SUFFIX,azureedge.net,微软服务
  - DOMAIN-SUFFIX,azurerms.com,微软服务
  - DOMAIN-SUFFIX,bing.com,微软服务
  - DOMAIN-SUFFIX,cloudapp.net,微软服务
  - DOMAIN-SUFFIX,cloudappsecurity.com,微软服务
  - DOMAIN-SUFFIX,edgesuite.net,微软服务
  - DOMAIN-SUFFIX,gfx.ms,微软服务
  - DOMAIN-SUFFIX,hotmail.com,微软服务
  - DOMAIN-SUFFIX,live.com,微软服务
  - DOMAIN-SUFFIX,live.net,微软服务
  - DOMAIN-SUFFIX,lync.com,微软服务
  - DOMAIN-SUFFIX,msappproxy.net,微软服务
  - DOMAIN-SUFFIX,msauth.net,微软服务
  - DOMAIN-SUFFIX,msauthimages.net,微软服务
  - DOMAIN-SUFFIX,msecnd.net,微软服务
  - DOMAIN-SUFFIX,msedge.net,微软服务
  - DOMAIN-SUFFIX,msft.net,微软服务
  - DOMAIN-SUFFIX,msftauth.net,微软服务
  - DOMAIN-SUFFIX,msftauthimages.net,微软服务
  - DOMAIN-SUFFIX,msftidentity.com,微软服务
  - DOMAIN-SUFFIX,msidentity.com,微软服务
  - DOMAIN-SUFFIX,msn.com,微软服务
  - DOMAIN-SUFFIX,msocdn.com,微软服务
  - DOMAIN-SUFFIX,msocsp.com,微软服务
  - DOMAIN-SUFFIX,mstea.ms,微软服务
  - DOMAIN-SUFFIX,o365weve.com,微软服务
  - DOMAIN-SUFFIX,oaspapps.com,微软服务
  - DOMAIN-SUFFIX,office.com,微软服务
  - DOMAIN-SUFFIX,office.net,微软服务
  - DOMAIN-SUFFIX,office365.com,微软服务
  - DOMAIN-SUFFIX,officeppe.net,微软服务
  - DOMAIN-SUFFIX,omniroot.com,微软服务
  - DOMAIN-SUFFIX,onedrive.com,微软服务
  - DOMAIN-SUFFIX,onenote.com,微软服务
  - DOMAIN-SUFFIX,onenote.net,微软服务
  - DOMAIN-SUFFIX,onestore.ms,微软服务
  - DOMAIN-SUFFIX,outlook.com,微软服务
  - DOMAIN-SUFFIX,outlookmobile.com,微软服务
  - DOMAIN-SUFFIX,phonefactor.net,微软服务
  - DOMAIN-SUFFIX,public-trust.com,微软服务
  - DOMAIN-SUFFIX,sfbassets.com,微软服务
  - DOMAIN-SUFFIX,sfx.ms,微软服务
  - DOMAIN-SUFFIX,sharepoint.com,微软服务
  - DOMAIN-SUFFIX,sharepointonline.com,微软服务
  - DOMAIN-SUFFIX,skype.com,微软服务
  - DOMAIN-SUFFIX,skypeassets.com,微软服务
  - DOMAIN-SUFFIX,skypeforbusiness.com,微软服务
  - DOMAIN-SUFFIX,staffhub.ms,微软服务
  - DOMAIN-SUFFIX,svc.ms,微软服务
  - DOMAIN-SUFFIX,sway-cdn.com,微软服务
  - DOMAIN-SUFFIX,sway-extensions.com,微软服务
  - DOMAIN-SUFFIX,sway.com,微软服务
  - DOMAIN-SUFFIX,trafficmanager.net,微软服务
  - DOMAIN-SUFFIX,uservoice.com,微软服务
  - DOMAIN-SUFFIX,virtualearth.net,微软服务
  - DOMAIN-SUFFIX,visualstudio.com,微软服务
  - DOMAIN-SUFFIX,windows-ppe.net,微软服务
  - DOMAIN-SUFFIX,windows.com,微软服务
  - DOMAIN-SUFFIX,windows.net,微软服务
  - DOMAIN-SUFFIX,windowsazure.com,微软服务
  - DOMAIN-SUFFIX,windowsupdate.com,微软服务
  - DOMAIN-SUFFIX,wunderlist.com,微软服务
  - DOMAIN-SUFFIX,yammer.com,微软服务
  - DOMAIN-SUFFIX,yammerusercontent.com,微软服务

  - DOMAIN-KEYWORD,youtube,谷歌服务
  - DOMAIN,youtubei.googleapis.com,谷歌服务
  - DOMAIN,yt3.ggpht.com,谷歌服务
  - DOMAIN-SUFFIX,googlevideo.com,谷歌服务
  - DOMAIN-SUFFIX,gvt2.com,谷歌服务
  - DOMAIN-SUFFIX,youtu.be,谷歌服务
  - DOMAIN-SUFFIX,youtube.com,谷歌服务
  - DOMAIN-SUFFIX,ytimg.com,谷歌服务

  - DOMAIN-KEYWORD,twitter,社交服务
  - DOMAIN-SUFFIX,ads-twitter.com,社交服务
  - DOMAIN-SUFFIX,berlintwitterwall.com,社交服务
  - DOMAIN-SUFFIX,financetwitter.com,社交服务
  - DOMAIN-SUFFIX,simbolostwitter.com,社交服务
  - DOMAIN-SUFFIX,turbotwitter.com,社交服务
  - DOMAIN-SUFFIX,twitter.com,社交服务
  - DOMAIN-SUFFIX,twitter.jp,社交服务
  - DOMAIN-SUFFIX,tweetbackup.com,🚀 节点选择
  - DOMAIN-SUFFIX,tweetboard.com,🚀 节点选择
  - DOMAIN-SUFFIX,tweetboner.biz,🚀 节点选择
  - DOMAIN-SUFFIX,tweetcs.com,🚀 节点选择
  - DOMAIN-SUFFIX,tweetdeck.com,🚀 节点选择
  - DOMAIN-SUFFIX,tweetedtimes.com,🚀 节点选择
  - DOMAIN-SUFFIX,tweetmylast.fm,🚀 节点选择
  - DOMAIN-SUFFIX,tweetphoto.com,🚀 节点选择
  - DOMAIN-SUFFIX,tweetrans.com,🚀 节点选择
  - DOMAIN-SUFFIX,tweetree.com,🚀 节点选择
  - DOMAIN-SUFFIX,tweettunnel.com,🚀 节点选择
  - DOMAIN-SUFFIX,tweetwally.com,🚀 节点选择
  - DOMAIN-SUFFIX,tweetymail.com,🚀 节点选择
  - DOMAIN-SUFFIX,tweez.net,🚀 节点选择
  - DOMAIN-SUFFIX,twelve.today,🚀 节点选择
  - DOMAIN-SUFFIX,twerkingbutt.com,🚀 节点选择
  - DOMAIN-SUFFIX,twftp.org,🚀 节点选择
  - DOMAIN-SUFFIX,twgreatdaily.com,🚀 节点选择
  - DOMAIN-SUFFIX,twibase.com,🚀 节点选择
  - DOMAIN-SUFFIX,twibble.de,🚀 节点选择
  - DOMAIN-SUFFIX,twibbon.com,🚀 节点选择
  - DOMAIN-SUFFIX,twibs.com,🚀 节点选择
  - DOMAIN-SUFFIX,twicountry.org,🚀 节点选择
  - DOMAIN-SUFFIX,twicsy.com,🚀 节点选择
  - DOMAIN-SUFFIX,twiends.com,🚀 节点选择
  - DOMAIN-SUFFIX,twifan.com,🚀 节点选择
  - DOMAIN-SUFFIX,twiffo.com,🚀 节点选择
  - DOMAIN-SUFFIX,twiggit.org,🚀 节点选择
  - DOMAIN-SUFFIX,twilightsex.com,🚀 节点选择
  - DOMAIN-SUFFIX,twilio.com,🚀 节点选择
  - DOMAIN-SUFFIX,twilog.org,🚀 节点选择
  - DOMAIN-SUFFIX,twimbow.com,🚀 节点选择
  - DOMAIN-SUFFIX,twimg.com,🚀 节点选择
  - DOMAIN-SUFFIX,twindexx.com,🚀 节点选择
  - DOMAIN-SUFFIX,twip.me,🚀 节点选择
  - DOMAIN-SUFFIX,twipple.jp,🚀 节点选择
  - DOMAIN-SUFFIX,twishort.com,🚀 节点选择
  - DOMAIN-SUFFIX,twistar.cc,🚀 节点选择
  - DOMAIN-SUFFIX,twister.net.co,🚀 节点选择
  - DOMAIN-SUFFIX,twisterio.com,🚀 节点选择
  - DOMAIN-SUFFIX,twisternow.com,🚀 节点选择
  - DOMAIN-SUFFIX,twistory.net,🚀 节点选择
  - DOMAIN-SUFFIX,twit2d.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitbrowser.net,🚀 节点选择
  - DOMAIN-SUFFIX,twitcause.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitch.tv,🚀 节点选择
  - DOMAIN-SUFFIX,twitchcdn.net,🚀 节点选择
  - DOMAIN-SUFFIX,twitgether.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitgoo.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitiq.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitlonger.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitmania.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitoaster.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitonmsn.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitpic.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitstat.com,🚀 节点选择
  - DOMAIN-SUFFIX,twittbot.net,🚀 节点选择
  - DOMAIN-SUFFIX,twitter4j.org,🚀 节点选择
  - DOMAIN-SUFFIX,twittercounter.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitterfeed.com,🚀 节点选择
  - DOMAIN-SUFFIX,twittergadget.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitterkr.com,🚀 节点选择
  - DOMAIN-SUFFIX,twittermail.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitterrific.com,🚀 节点选择
  - DOMAIN-SUFFIX,twittertim.es,🚀 节点选择
  - DOMAIN-SUFFIX,twitthat.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitturk.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitturly.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitvid.com,🚀 节点选择
  - DOMAIN-SUFFIX,twitzap.com,🚀 节点选择
  - DOMAIN-SUFFIX,twiyia.com,🚀 节点选择

  - RULE-SET,Proxy,节点选择
  - RULE-SET,Reject,REJECT
  - RULE-SET,Private,REJECT
  - RULE-SET,iCloud,苹果服务,no-resolve
  - RULE-SET,Apple,苹果服务,no-resolve
  - RULE-SET,Google,谷歌服务
  - RULE-SET,Telegram,社交服务

  - GEOIP,CN,DIRECT
  - MATCH,节点选择
