port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:

proxy-groups:
  - name: "Tier 1 🚀"
    type: select
    proxies:
  - name: "Tier 2 ⚡️"
    type: select
    proxies:
  - name: "Tier 3 💎"
    type: select
    proxies:
  - name: "Tier 4 🗿"
    type: select
    proxies:
    
rules:
  - MATCH,Tier 4 🗿
  - MATCH,Tier 3 💎
  - MATCH,Tier 2 ⚡️
  - MATCH,Tier 1 🚀
