name: test_ip

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Load Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Tehran'
      - name: Install Dependencies
        run: |
          pip install -r ./utils/requirements.txt
      - name: Run Ip Test
        run: |
          ip adress
          # Clash
          wget -O clash.gz https://github.com/Dreamacro/clash/releases/download/v1.11.8/clash-linux-amd64-v1.11.8.gz
          gunzip clash.gz
          wget -O lite-linux-amd64 https://github.com/mahdibland/SSAggregator/releases/download/1.0.0/lite-linux-amd64
          wget -O clash_config.yml https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/utils/speedtest/clash_config_eu.yml
          wget -O proxychains.conf https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/utils/speedtest/proxychains.conf
          wget -O lite_config.json https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/utils/speedtest/lite_config_yaml.json
          #初始化 Clash
          chmod +x ./clash && ./clash &
          #安装并配置 proxychains
          sudo apt-get install proxychains
          sudo chmod 777 ../../../../../../etc/proxychains.conf
          mv -f proxychains.conf ../../../../../../etc/proxychains.conf
          #开始运行 Clash
          sudo pkill -f clash
          ./clash -f clash_config.yml &
          ip address
          sudo proxychains ip address
